groups:
  - name: "automation"
    rules:
      # CPU usage alerts
      - alert: "HighCPUUsage"
        expr: "system_cpu_usage > 80"
        for: "5m"
        labels:
          severity: "warning"
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for 5 minutes"

      - alert: "CriticalCPUUsage"
        expr: "system_cpu_usage > 90"
        for: "2m"
        labels:
          severity: "critical"
        annotations:
          summary: "Critical CPU usage detected"
          description: "CPU usage is above 90% for 2 minutes"

      # Memory usage alerts
      - alert: "HighMemoryUsage"
        expr: "system_memory_usage > 80"
        for: "5m"
        labels:
          severity: "warning"
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 80% for 5 minutes"

      - alert: "CriticalMemoryUsage"
        expr: "system_memory_usage > 90"
        for: "2m"
        labels:
          severity: "critical"
        annotations:
          summary: "Critical memory usage detected"
          description: "Memory usage is above 90% for 2 minutes"

      # Disk usage alerts
      - alert: "HighDiskUsage"
        expr: "system_disk_usage > 80"
        for: "5m"
        labels:
          severity: "warning"
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is above 80% for 5 minutes"

      - alert: "CriticalDiskUsage"
        expr: "system_disk_usage > 90"
        for: "2m"
        labels:
          severity: "critical"
        annotations:
          summary: "Critical disk usage detected"
          description: "Disk usage is above 90% for 2 minutes"

      # Task execution alerts
      - alert: "HighTaskFailureRate"
        expr: "rate(task_failure_total[5m]) / rate(task_success_total[5m]) > 0.1"
        for: "5m"
        labels:
          severity: "warning"
        annotations:
          summary: "High task failure rate detected"
          description: "Task failure rate is above 10% for 5 minutes"

      - alert: "CriticalTaskFailureRate"
        expr: "rate(task_failure_total[5m]) / rate(task_success_total[5m]) > 0.3"
        for: "2m"
        labels:
          severity: "critical"
        annotations:
          summary: "Critical task failure rate detected"
          description: "Task failure rate is above 30% for 2 minutes"

      # API performance alerts
      - alert: "HighAPILatency"
        expr: "rate(api_request_duration_seconds_sum[5m]) / rate(api_request_duration_seconds_count[5m]) > 1"
        for: "5m"
        labels:
          severity: "warning"
        annotations:
          summary: "High API latency detected"
          description: "API request duration is above 1 second for 5 minutes"

      - alert: "CriticalAPILatency"
        expr: "rate(api_request_duration_seconds_sum[5m]) / rate(api_request_duration_seconds_count[5m]) > 2"
        for: "2m"
        labels:
          severity: "critical"
        annotations:
          summary: "Critical API latency detected"
          description: "API request duration is above 2 seconds for 2 minutes"

      # Service health alerts
      - alert: "ServiceDown"
        expr: "up == 0"
        for: "1m"
        labels:
          severity: "critical"
        annotations:
          summary: "Service is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute"

      - alert: "ServiceHighErrorRate"
        expr: "rate(http_requests_total{status=~\"5..\"}[5m]) / rate(http_requests_total[5m]) > 0.1"
        for: "5m"
        labels:
          severity: "warning"
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for 5 minutes"

      # Resource exhaustion alerts
      - alert: "MemoryExhaustion"
        expr: "system_memory_usage > 95"
        for: "1m"
        labels:
          severity: "critical"
        annotations:
          summary: "Memory exhaustion detected"
          description: "Memory usage is above 95% for 1 minute"

      - alert: "DiskExhaustion"
        expr: "system_disk_usage > 95"
        for: "1m"
        labels:
          severity: "critical"
        annotations:
          summary: "Disk exhaustion detected"
          description: "Disk usage is above 95% for 1 minute"

      # Network alerts
      - alert: "HighNetworkLatency"
        expr: "rate(network_latency_seconds_sum[5m]) / rate(network_latency_seconds_count[5m]) > 0.5"
        for: "5m"
        labels:
          severity: "warning"
        annotations:
          summary: "High network latency detected"
          description: "Network latency is above 500ms for 5 minutes"

      - alert: "HighNetworkErrors"
        expr: "rate(network_errors_total[5m]) > 0"
        for: "5m"
        labels:
          severity: "warning"
        annotations:
          summary: "Network errors detected"
          description: "Network errors are occurring for 5 minutes" 