repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        language_version: python3.10

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-docstrings',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-simplify',
            'flake8-import-order',
        ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            'types-requests',
            'types-PyYAML',
            'types-python-dateutil',
            'types-pytz',
            'types-setuptools',
        ]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, md, yaml]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.2
    hooks:
    -   id: pylint
        additional_dependencies: [
            'pylint-pytest',
            'pylint-pytest-plugin',
        ] 