# Trading System Configuration

# Data settings
data:
  source: "${DATA_SOURCE:-yahoo}"  # Data source (yahoo, alpha_vantage, etc.)
  symbols: "${SYMBOLS:-['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']}"
  timeframe: "${TIMEFRAME:-1d}"  # Data timeframe
  start_date: "${START_DATE:-2020-01-01}"
  end_date: "${END_DATE:-2023-12-31}"
  features: "${FEATURES:-['open', 'high', 'low', 'close', 'volume', 'adj_close']}"

# Feature engineering settings
feature_engineering:
  technical_indicators:
    - name: "SMA"
      windows: "${SMA_WINDOWS:-[20, 50, 200]}"
    - name: "EMA"
      windows: "${EMA_WINDOWS:-[12, 26]}"
    - name: "RSI"
      window: "${RSI_WINDOW:-14}"
    - name: "MACD"
      fast_period: "${MACD_FAST_PERIOD:-12}"
      slow_period: "${MACD_SLOW_PERIOD:-26}"
      signal_period: "${MACD_SIGNAL_PERIOD:-9}"
    - name: "Bollinger Bands"
      window: "${BB_WINDOW:-20}"
      num_std: "${BB_NUM_STD:-2}"
  statistical_features:
    - name: "returns"
      method: "${RETURNS_METHOD:-log}"
    - name: "volatility"
      window: "${VOLATILITY_WINDOW:-252}"
    - name: "skewness"
      window: "${SKEWNESS_WINDOW:-252}"
    - name: "kurtosis"
      window: "${KURTOSIS_WINDOW:-252}"
  market_microstructure:
    - name: "bid_ask_spread"
      window: "${BID_ASK_WINDOW:-20}"
    - name: "order_flow_imbalance"
      window: "${ORDER_FLOW_WINDOW:-20}"
    - name: "volume_profile"
      num_bins: "${VOLUME_PROFILE_BINS:-10}"
  time_features:
    - name: "hour"
    - name: "day_of_week"
    - name: "month"
    - name: "is_month_end"
    - name: "is_quarter_end"
    - name: "is_year_end"

# Model settings
model:
  type: "${MODEL_TYPE:-dqn}"  # Model type (dqn, lstm, transformer)
  state_dim: "${STATE_DIM:-50}"  # State dimension
  action_dim: "${ACTION_DIM:-3}"  # Action dimension (buy, sell, hold)
  hidden_size: "${HIDDEN_SIZE:-128}"
  learning_rate: "${LEARNING_RATE:-0.001}"
  batch_size: "${BATCH_SIZE:-64}"
  gamma: "${GAMMA:-0.99}"
  epsilon_start: "${EPSILON_START:-1.0}"
  epsilon_end: "${EPSILON_END:-0.01}"
  epsilon_decay: "${EPSILON_DECAY:-0.995}"
  memory_size: "${MEMORY_SIZE:-10000}"
  target_update: "${TARGET_UPDATE:-10}"
  gradient_clip: "${GRADIENT_CLIP:-1.0}"
  dropout: "${DROPOUT:-0.2}"
  num_layers: "${NUM_LAYERS:-2}"
  num_heads: "${NUM_HEADS:-4}"  # For transformer
  warmup_steps: "${WARMUP_STEPS:-1000}"
  max_epochs: "${MAX_EPOCHS:-1000}"
  early_stopping:
    patience: "${EARLY_STOPPING_PATIENCE:-10}"
    min_delta: "${EARLY_STOPPING_MIN_DELTA:-0.001}"

# Strategy settings
strategy:
  type: "${STRATEGY_TYPE:-ensemble}"  # Strategy type (single, ensemble)
  strategies:
    - name: "trend_following"
      weight: "${TREND_FOLLOWING_WEIGHT:-0.4}"
    - name: "mean_reversion"
      weight: "${MEAN_REVERSION_WEIGHT:-0.3}"
    - name: "breakout"
      weight: "${BREAKOUT_WEIGHT:-0.3}"
  position_sizing:
    method: "${POSITION_SIZING_METHOD:-kelly}"  # Position sizing method (fixed, kelly, optimal)
    max_position_size: "${MAX_POSITION_SIZE:-0.2}"  # Maximum position size as fraction of portfolio
    risk_per_trade: "${RISK_PER_TRADE:-0.02}"  # Risk per trade as fraction of portfolio

# Risk management settings
risk:
  position_limits:
    max_position_size: "${MAX_POSITION_SIZE_LIMIT:-0.2}"
    max_leverage: "${MAX_LEVERAGE_LIMIT:-2.0}"
    max_correlation: "${MAX_CORRELATION_LIMIT:-0.7}"
  risk_limits:
    max_drawdown: "${MAX_DRAWDOWN_LIMIT:-0.2}"
    max_volatility: "${MAX_VOLATILITY_LIMIT:-0.3}"
    min_sharpe_ratio: "${MIN_SHARPE_RATIO:-1.0}"
    var_confidence: "${VAR_CONFIDENCE:-0.95}"
  portfolio_limits:
    max_sector_exposure: "${MAX_SECTOR_EXPOSURE:-0.3}"
    max_country_exposure: "${MAX_COUNTRY_EXPOSURE:-0.4}"
    min_diversification: "${MIN_DIVERSIFICATION:-0.7}"

# Portfolio management settings
portfolio:
  initial_cash: "${INITIAL_CASH:-100000}"
  rebalance_frequency: "${REBALANCE_FREQUENCY:-monthly}"
  rebalance_threshold: "${REBALANCE_THRESHOLD:-0.1}"
  transaction_cost: "${TRANSACTION_COST:-0.001}"
  slippage: "${SLIPPAGE:-0.0005}"
  tax_rate: "${TAX_RATE:-0.15}"
  dividend_reinvestment: "${DIVIDEND_REINVESTMENT:-true}"

# Optimization settings
optimization:
  method: "${OPTIMIZATION_METHOD:-bayesian}"  # Optimization method (grid, random, bayesian)
  objective: "${OPTIMIZATION_OBJECTIVE:-sharpe_ratio}"  # Optimization objective
  constraints:
    - "max_drawdown < 0.2"
    - "volatility < 0.3"
    - "sharpe_ratio > 1.0"
  parameters:
    - name: "lookback_window"
      min: "${LOOKBACK_WINDOW_MIN:-10}"
      max: "${LOOKBACK_WINDOW_MAX:-200}"
    - name: "entry_threshold"
      min: "${ENTRY_THRESHOLD_MIN:-0.01}"
      max: "${ENTRY_THRESHOLD_MAX:-0.1}"
    - name: "exit_threshold"
      min: "${EXIT_THRESHOLD_MIN:-0.01}"
      max: "${EXIT_THRESHOLD_MAX:-0.1}"
    - name: "stop_loss"
      min: "${STOP_LOSS_MIN:-0.01}"
      max: "${STOP_LOSS_MAX:-0.1}"
    - name: "take_profit"
      min: "${TAKE_PROFIT_MIN:-0.01}"
      max: "${TAKE_PROFIT_MAX:-0.2}"

# Backtesting settings
backtesting:
  start_date: "${BACKTEST_START_DATE:-2020-01-01}"
  end_date: "${BACKTEST_END_DATE:-2023-12-31}"
  initial_cash: "${BACKTEST_INITIAL_CASH:-100000}"
  transaction_cost: "${BACKTEST_TRANSACTION_COST:-0.001}"
  slippage: "${BACKTEST_SLIPPAGE:-0.0005}"
  benchmark: "${BACKTEST_BENCHMARK:-SPY}"
  metrics:
    - "total_return"
    - "annualized_return"
    - "volatility"
    - "sharpe_ratio"
    - "sortino_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
    - "calmar_ratio"
    - "information_ratio"

# Logging settings
logging:
  level: "${LOG_LEVEL:-INFO}"
  file: "${LOG_FILE:-trading.log}"
  max_size: "${LOG_MAX_SIZE:-10485760}"
  backup_count: "${LOG_BACKUP_COUNT:-5}"

# API settings
api:
  yahoo:
    retry_count: "${YAHOO_RETRY_COUNT:-3}"
    timeout: "${YAHOO_TIMEOUT:-30}"
  alpha_vantage:
    api_key: "${ALPHA_VANTAGE_API_KEY}"
    retry_count: "${ALPHA_VANTAGE_RETRY_COUNT:-3}"
    timeout: "${ALPHA_VANTAGE_TIMEOUT:-30}"
  polygon:
    api_key: "${POLYGON_API_KEY}"
    retry_count: "${POLYGON_RETRY_COUNT:-3}"
    timeout: "${POLYGON_TIMEOUT:-30}"

# System settings
system:
  num_workers: "${NUM_WORKERS:-4}"
  use_gpu: "${USE_GPU:-true}"
  seed: "${SEED:-42}"
  cache_dir: "${CACHE_DIR:-cache}"
  results_dir: "${RESULTS_DIR:-results}"
  checkpoint_dir: "${CHECKPOINT_DIR:-checkpoints}"
  tensorboard_dir: "${TENSORBOARD_DIR:-tensorboard}"

api_keys:
  alpha_vantage: "${ALPHA_VANTAGE_API_KEY}"
  polygon: "${POLYGON_API_KEY}"
  finnhub: "${FINNHUB_API_KEY}"
  iex: "${IEX_API_KEY}"
  twilio: "${TWILIO_API_KEY}"
  sendgrid: "${SENDGRID_API_KEY}"

redis:
  host: "${REDIS_HOST:-localhost}"
  port: "${REDIS_PORT:-6379}"
  db: "${REDIS_DB:-0}"
  password: "${REDIS_PASSWORD}"
  ssl: "${REDIS_SSL:-false}"

ray:
  address: "${RAY_ADDRESS:-auto}"
  redis_password: "${RAY_REDIS_PASSWORD}"
  num_cpus: "${RAY_NUM_CPUS:-4}"
  num_gpus: "${RAY_NUM_GPUS:-0}"

kubernetes:
  namespace: "${K8S_NAMESPACE:-default}"
  service_account: "${K8S_SERVICE_ACCOUNT:-default}"

metrics:
  enabled: "${METRICS_ENABLED:-true}"
  port: "${METRICS_PORT:-9090}"
  path: "${METRICS_PATH:-/metrics}"

agents:
  max_workers: "${MAX_WORKERS:-10}"
  timeout: "${AGENT_TIMEOUT:-300}"
  retry_attempts: "${RETRY_ATTEMPTS:-3}"

tasks:
  max_concurrent: "${MAX_CONCURRENT_TASKS:-5}"
  default_timeout: "${TASK_TIMEOUT:-3600}"

web:
  host: "${WEB_HOST:-0.0.0.0}"
  port: "${WEB_PORT:-5000}"
  debug: "${WEB_DEBUG:-false}"
  secret_key: "${WEB_SECRET_KEY}"
  jwt_secret: "${JWT_SECRET}"
  ssl_cert: "${SSL_CERT:-}"
  ssl_key: "${SSL_KEY:-}"
  cors_origins: "${CORS_ORIGINS:-*}"
  rate_limit: "${RATE_LIMIT:-100}"
  rate_limit_window: "${RATE_LIMIT_WINDOW:-3600}" 