# Evolve Trading Platform - Production Deployment Configuration

# Application Settings
app:
  name: "evolve-trading-platform"
  version: "1.0.0"
  entry_point: "unified_interface.py"
  port: 8501
  host: "0.0.0.0"

# Streamlit Configuration
streamlit:
  server:
    address: "0.0.0.0"
    port: 8501
    enableCORS: false
    enableXsrfProtection: false
  browser:
    gatherUsageStats: false
  theme:
    primaryColor: "#FF6B6B"
    backgroundColor: "#FFFFFF"
    secondaryBackgroundColor: "#F0F2F6"
    textColor: "#262730"

# Environment Variables
environment:
  required:
    - "OPENAI_API_KEY"
    - "ALPHA_VANTAGE_API_KEY"
    - "BINANCE_API_KEY"
    - "BINANCE_SECRET_KEY"
  optional:
    - "REDIS_URL"
    - "DATABASE_URL"
    - "SLACK_WEBHOOK_URL"
    - "EMAIL_PASSWORD"

# Dependencies
dependencies:
  python_version: "3.10"
  packages:
    - "streamlit>=1.28.0"
    - "pandas>=2.0.0"
    - "numpy>=1.24.0"
    - "plotly>=5.15.0"
    - "scikit-learn>=1.3.0"
    - "prophet>=1.1.0"
    - "xgboost>=1.7.0"
    - "yfinance>=0.2.0"
    - "pandas-ta>=0.3.14b0"
    - "openai>=1.0.0"
    - "redis>=4.5.0"
    - "psycopg2-binary>=2.9.0"
    - "pytest>=7.4.0"
    - "pytest-cov>=4.1.0"

# Health Check Configuration
health_check:
  endpoint: "/_stcore/health"
  interval: 30
  timeout: 10
  retries: 3

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "file"
      filename: "logs/app.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5
    - type: "stream"
      level: "INFO"

# Security Configuration
security:
  cors_origins: ["*"]
  allowed_hosts: ["*"]
  rate_limiting:
    enabled: true
    requests_per_minute: 100
  api_keys:
    required: true
    validation: true

# Performance Configuration
performance:
  cache:
    enabled: true
    ttl: 3600  # 1 hour
    max_size: 1000
  optimization:
    enable_gpu: true
    enable_parallel: true
    max_workers: 4

# Monitoring Configuration
monitoring:
  metrics:
    enabled: true
    endpoint: "/metrics"
  alerts:
    enabled: true
    channels:
      - "email"
      - "slack"
    thresholds:
      error_rate: 0.05
      response_time: 5.0
      memory_usage: 0.8

# Backup Configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
  storage:
    type: "local"
    path: "backups/"

# Testing Configuration
testing:
  coverage_threshold: 80
  test_timeout: 300
  parallel_tests: true
  test_pattern: "test_*.py"

# Documentation
documentation:
  api_docs: true
  user_guide: true
  deployment_guide: true
  troubleshooting_guide: true 