# Application Configuration

# Server Settings
server:
  host: "${HOST:-0.0.0.0}"
  port: "${PORT:-8501}"
  debug: "${DEBUG_MODE:-false}"
  workers: "${WORKERS:-4}"
  timeout: "${TIMEOUT:-60}"
  reload: "${RELOAD:-false}"
  access_log: "${ACCESS_LOG:-true}"

# Logging Configuration
logging:
  level: "${LOG_LEVEL:-INFO}"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "${LOG_FILE:-logs/app.log}"
  max_size: "${LOG_MAX_SIZE:-10485760}"  # 10MB
  backup_count: "${LOG_BACKUP_COUNT:-5}"
  console: "${LOG_CONSOLE:-true}"
  json_format: "${LOG_JSON:-false}"

# Database Settings
database:
  redis:
    host: "${REDIS_HOST:-localhost}"
    port: "${REDIS_PORT:-6379}"
    db: "${REDIS_DB:-0}"
    password: "${REDIS_PASSWORD:-null}"
    ssl: "${REDIS_SSL:-false}"
    pool_size: "${REDIS_POOL_SIZE:-10}"
    retry_on_timeout: "${REDIS_RETRY_TIMEOUT:-true}"
  sqlite:
    path: "${SQLITE_PATH:-data/trading.db}"
    timeout: "${SQLITE_TIMEOUT:-30}"

# Market Data Settings
market_data:
  default_timeframe: "${DEFAULT_TIMEFRAME:-1d}"
  default_assets: "${DEFAULT_ASSETS:-['BTC', 'ETH', 'SOL']}"
  cache_ttl: "${CACHE_TTL:-300}"  # 5 minutes
  max_retries: "${MAX_RETRIES:-3}"
  retry_delay: "${RETRY_DELAY:-1}"
  providers:
    - name: "yfinance"
      enabled: "${YFINANCE_ENABLED:-true}"
      rate_limit: "${YFINANCE_RATE_LIMIT:-100}"
    - name: "alpha_vantage"
      enabled: "${ALPHA_VANTAGE_ENABLED:-false}"
      api_key: "${ALPHA_VANTAGE_API_KEY:-null}"
      rate_limit: "${ALPHA_VANTAGE_RATE_LIMIT:-5}"

# Model Settings
models:
  forecast:
    horizon: "${FORECAST_HORIZON:-30}"  # days
    confidence_interval: "${CONFIDENCE_INTERVAL:-0.95}"
    min_training_samples: "${MIN_TRAINING_SAMPLES:-1000}"
    update_frequency: "${UPDATE_FREQUENCY:-3600}"  # 1 hour
    ensemble_size: "${ENSEMBLE_SIZE:-5}"
    validation_split: "${VALIDATION_SPLIT:-0.2}"
  technical:
    indicators:
      - name: "RSI"
        period: "${RSI_PERIOD:-14}"
        overbought: "${RSI_OVERBOUGHT:-70}"
        oversold: "${RSI_OVERSOLD:-30}"
      - name: "MACD"
        fast_period: "${MACD_FAST_PERIOD:-12}"
        slow_period: "${MACD_SLOW_PERIOD:-26}"
        signal_period: "${MACD_SIGNAL_PERIOD:-9}"
      - name: "BB"
        period: "${BB_PERIOD:-20}"
        std_dev: "${BB_STD_DEV:-2}"
      - name: "ATR"
        period: "${ATR_PERIOD:-14}"
      - name: "ADX"
        period: "${ADX_PERIOD:-14}"

# Strategy Settings
strategies:
  default:
    position_size: "${POSITION_SIZE:-0.1}"
    stop_loss: "${STOP_LOSS:-0.02}"
    take_profit: "${TAKE_PROFIT:-0.04}"
    max_positions: "${MAX_POSITIONS:-5}"
    rebalance_frequency: "${REBALANCE_FREQUENCY:-1d}"
  optimization:
    method: "${OPTIMIZATION_METHOD:-bayesian}"
    n_trials: "${N_TRIALS:-100}"
    cv_folds: "${CV_FOLDS:-5}"
    timeout: "${OPTIMIZATION_TIMEOUT:-3600}"
    parallel_jobs: "${PARALLEL_JOBS:-4}"

# Risk Management
risk:
  max_drawdown: "${MAX_DRAWDOWN:-0.2}"
  max_leverage: "${MAX_LEVERAGE:-3}"
  position_limits:
    BTC: "${BTC_LIMIT:-0.3}"
    ETH: "${ETH_LIMIT:-0.3}"
    SOL: "${SOL_LIMIT:-0.2}"
    default: "${DEFAULT_LIMIT:-0.1}"
  correlation_threshold: "${CORRELATION_THRESHOLD:-0.7}"
  var_confidence: "${VAR_CONFIDENCE:-0.95}"
  stress_test_scenarios: "${STRESS_TEST_SCENARIOS:-10}"

# Portfolio Management
portfolio:
  max_weight: "${MAX_WEIGHT:-0.3}"
  min_weight: "${MIN_WEIGHT:-0.01}"
  target_volatility: "${TARGET_VOLATILITY:-0.15}"
  risk_free_rate: "${RISK_FREE_RATE:-0.02}"
  max_iterations: "${MAX_ITERATIONS:-1000}"
  tolerance: "${TOLERANCE:-1e-6}"
  kelly_fraction: "${KELLY_FRACTION:-0.25}"
  max_kelly_weight: "${MAX_KELLY_WEIGHT:-0.5}"

risk_management:
  max_drawdown: "${MAX_DRAWDOWN:-0.15}"
  max_exposure: "${MAX_EXPOSURE:-0.3}"
  max_leverage: "${MAX_LEVERAGE:-2.0}"
  target_volatility: "${TARGET_VOLATILITY:-0.15}"
  var_limit: "${VAR_LIMIT:-0.02}"
  max_correlation: "${MAX_CORRELATION:-0.7}"
  sector_limit: "${SECTOR_LIMIT:-0.4}"
  liquidity_limit: "${LIQUIDITY_LIMIT:-0.1}"
  var_confidence: "${VAR_CONFIDENCE:-0.95}"
  lookback_period: "${LOOKBACK_PERIOD:-252}"
  rebalancing_frequency: "${REBALANCING_FREQUENCY:-daily}"

# Execution Engine Settings
execution:
  mode: "${EXECUTION_MODE:-simulation}"  # simulation, live, paper
  spread_multiplier: "${SPREAD_MULTIPLIER:-1.0}"
  slippage_bps: "${SLIPPAGE_BPS:-5}"
  execution_delay_ms: "${EXECUTION_DELAY_MS:-100}"
  commission_rate: "${COMMISSION_RATE:-0.001}"
  min_commission: "${MIN_COMMISSION:-1.0}"
  max_position_size: "${MAX_POSITION_SIZE:-0.1}"
  max_order_size: "${MAX_ORDER_SIZE:-10000}"
  max_daily_trades: "${MAX_DAILY_TRADES:-100}"
  market_volatility: "${MARKET_VOLATILITY:-0.02}"
  price_impact_factor: "${PRICE_IMPACT_FACTOR:-0.0001}"
  broker:
    type: "${BROKER_TYPE:-simulation}"
    alpaca:
      api_key: "${ALPACA_API_KEY:-null}"
      secret_key: "${ALPACA_SECRET_KEY:-null}"
      base_url: "${ALPACA_BASE_URL:-https://paper-api.alpaca.markets}"
    ibkr:
      host: "${IBKR_HOST:-127.0.0.1}"
      port: "${IBKR_PORT:-7497}"
      client_id: "${IBKR_CLIENT_ID:-1}"
    polygon:
      api_key: "${POLYGON_API_KEY:-null}"

# Audit Trail Settings
audit:
  output_formats: "${AUDIT_OUTPUT_FORMATS:-['json', 'csv']}"
  batch_size: "${AUDIT_BATCH_SIZE:-100}"
  flush_interval: "${AUDIT_FLUSH_INTERVAL:-60}"  # seconds
  max_events: "${AUDIT_MAX_EVENTS:-10000}"
  real_time_logging: "${AUDIT_REAL_TIME_LOGGING:-true}"
  log_to_console: "${AUDIT_LOG_TO_CONSOLE:-false}"
  enabled_event_types: "${AUDIT_ENABLED_EVENTS:-['signal_generated', 'model_selected', 'forecast_made', 'trade_decision', 'order_submitted', 'order_executed', 'risk_check']}"
  min_confidence_threshold: "${AUDIT_MIN_CONFIDENCE:-0.0}"
  session_retention_days: "${AUDIT_RETENTION_DAYS:-30}"

# Explainability Settings
explainer:
  llm_enabled: "${EXPLAINER_LLM_ENABLED:-false}"
  llm_model: "${EXPLAINER_LLM_MODEL:-gpt-3.5-turbo}"
  llm_max_tokens: "${EXPLAINER_LLM_MAX_TOKENS:-500}"
  llm_temperature: "${EXPLAINER_LLM_TEMPERATURE:-0.7}"
  openai_api_key: "${OPENAI_API_KEY:-null}"
  explanation_levels: "${EXPLAINER_LEVELS:-['basic', 'detailed', 'expert']}"
  auto_explain: "${EXPLAINER_AUTO_EXPLAIN:-true}"
  explanation_retention_days: "${EXPLAINER_RETENTION_DAYS:-90}"
  performance_tracking: "${EXPLAINER_PERFORMANCE_TRACKING:-true}"

# Agent Settings
agents:
  goal_planner:
    enabled: "${GOAL_PLANNER_ENABLED:-true}"
    update_frequency: "${GOAL_UPDATE_FREQUENCY:-3600}"
    max_goals: "${MAX_GOALS:-10}"
  router:
    enabled: "${ROUTER_ENABLED:-true}"
    confidence_threshold: "${ROUTER_CONFIDENCE:-0.7}"
    fallback_agent: "${FALLBACK_AGENT:-commentary}"
  self_improving:
    enabled: "${SELF_IMPROVING_ENABLED:-true}"
    improvement_interval: "${IMPROVEMENT_INTERVAL:-86400}"  # 24 hours
    performance_thresholds:
      min_sharpe: "${MIN_SHARPE:-1.0}"
      max_drawdown: "${MAX_DRAWDOWN_THRESHOLD:-0.25}"
      min_accuracy: "${MIN_ACCURACY:-0.6}"

# NLP Settings
nlp:
  confidence_threshold: "${NLP_CONFIDENCE_THRESHOLD:-0.7}"
  max_tokens: "${NLP_MAX_TOKENS:-1000}"
  temperature: "${NLP_TEMPERATURE:-0.7}"
  cache_ttl: "${NLP_CACHE_TTL:-3600}"  # 1 hour
  models:
    - name: "gpt-3.5-turbo"
      enabled: "${GPT35_ENABLED:-true}"
      max_tokens: "${GPT35_MAX_TOKENS:-1000}"
    - name: "gpt-4"
      enabled: "${GPT4_ENABLED:-false}"
      max_tokens: "${GPT4_MAX_TOKENS:-2000}"
  templates:
    forecast: "${FORECAST_TEMPLATE:-trading/nlp/config/response_templates.json}"
    visualization: "${VIZ_TEMPLATE:-trading/nlp/config/viz_settings.json}"
    entities: "${ENTITY_TEMPLATE:-trading/nlp/config/entity_patterns.json}"
    intents: "${INTENT_TEMPLATE:-trading/nlp/config/intent_patterns.json}"

# API Settings
api:
  rate_limit: "${API_RATE_LIMIT:-100}"  # requests per minute
  timeout: "${API_TIMEOUT:-30}"
  max_retries: "${API_MAX_RETRIES:-3}"
  cache_ttl: "${API_CACHE_TTL:-300}"  # 5 minutes
  version: "${API_VERSION:-v1}"
  documentation: "${API_DOCS:-true}"

# Performance Monitoring
monitoring:
  enabled: "${MONITORING_ENABLED:-true}"
  metrics:
    - name: "response_time"
      threshold: "${RESPONSE_TIME_THRESHOLD:-2.0}"  # seconds
    - name: "memory_usage"
      threshold: "${MEMORY_USAGE_THRESHOLD:-1024}"  # MB
    - name: "cpu_usage"
      threshold: "${CPU_USAGE_THRESHOLD:-80}"  # percent
    - name: "error_rate"
      threshold: "${ERROR_RATE_THRESHOLD:-0.05}"  # 5%
  alert:
    email: "${ALERT_EMAIL:-alerts@example.com}"
    slack: "${ALERT_SLACK:-https://hooks.slack.com/services/xxx/yyy/zzz}"
    webhook: "${ALERT_WEBHOOK:-null}"
  dashboard:
    enabled: "${DASHBOARD_ENABLED:-true}"
    port: "${DASHBOARD_PORT:-8080}"
    refresh_interval: "${DASHBOARD_REFRESH:-30}"  # seconds

# Security Settings
security:
  ssl:
    enabled: "${SSL_ENABLED:-false}"
    cert_file: "${SSL_CERT_FILE:-null}"
    key_file: "${SSL_KEY_FILE:-null}"
  cors:
    allowed_origins: "${CORS_ORIGINS:-['*']}"
    allowed_methods: "${CORS_METHODS:-['GET', 'POST']}"
    allowed_headers: "${CORS_HEADERS:-['*']}"
  rate_limiting:
    enabled: "${RATE_LIMITING_ENABLED:-true}"
    window: "${RATE_LIMITING_WINDOW:-60}"  # seconds
    max_requests: "${RATE_LIMITING_MAX_REQUESTS:-100}"
  authentication:
    enabled: "${AUTH_ENABLED:-false}"
    jwt_secret: "${JWT_SECRET:-null}"
    token_expiry: "${TOKEN_EXPIRY:-3600}"  # 1 hour

# Development Settings
development:
  debug: "${DEV_DEBUG:-false}"
  hot_reload: "${HOT_RELOAD:-false}"
  profiling: "${PROFILING:-false}"
  test_mode: "${TEST_MODE:-false}"
  mock_data: "${MOCK_DATA:-false}" 