logging:
  # Log levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO
  
  # Log format
  format: "[%(asctime)s] [%(levelname)s] %(name)s: %(message)s"
  
  # Log files
  file: "logs/app.log"
  audit_file: "logs/audit.log"
  
  # Rotating file handler settings
  max_bytes: 5242880  # 5MB
  backup_count: 3
  
  # Module-specific log levels
  module_levels:
    trading.llm: DEBUG
    trading.strategies: INFO
    trading.rules: INFO
    trading.agents: DEBUG
    
  # Handler settings
  handlers:
    console:
      enabled: true
      level: INFO
    file:
      enabled: true
      level: INFO
    audit:
      enabled: true
      level: INFO 