# Strategies Configuration
# This file contains all trading strategy-related configuration settings

strategies:
  # General strategy settings
  enabled: true
  default_position_size: 0.1
  max_concurrent_strategies: 5
  strategy_rotation: true
  rotation_frequency_days: 7
  
  # Strategy definitions
  definitions:
    bollinger_bands:
      enabled: true
      description: "Bollinger Bands mean reversion strategy"
      parameters:
        lookback_period: 20
        std_dev: 2.0
        position_size: 0.1
        stop_loss: 0.05
        take_profit: 0.1
      signals:
        buy: "price_below_lower_band"
        sell: "price_above_upper_band"
        exit: "price_crosses_middle_band"
        
    macd:
      enabled: true
      description: "MACD momentum strategy"
      parameters:
        fast_period: 12
        slow_period: 26
        signal_period: 9
        position_size: 0.1
        stop_loss: 0.05
        take_profit: 0.1
      signals:
        buy: "macd_crosses_signal_up"
        sell: "macd_crosses_signal_down"
        exit: "macd_crosses_zero"
        
    rsi:
      enabled: true
      description: "RSI overbought/oversold strategy"
      parameters:
        period: 14
        oversold_threshold: 30
        overbought_threshold: 70
        position_size: 0.1
        stop_loss: 0.05
        take_profit: 0.1
      signals:
        buy: "rsi_below_oversold"
        sell: "rsi_above_overbought"
        exit: "rsi_crosses_50"
        
    moving_average_crossover:
      enabled: true
      description: "Moving average crossover strategy"
      parameters:
        fast_period: 10
        slow_period: 30
        position_size: 0.1
        stop_loss: 0.05
        take_profit: 0.1
      signals:
        buy: "fast_ma_crosses_slow_ma_up"
        sell: "fast_ma_crosses_slow_ma_down"
        exit: "price_crosses_fast_ma"
        
    mean_reversion:
      enabled: true
      description: "Mean reversion strategy"
      parameters:
        lookback_period: 20
        std_dev_threshold: 2.0
        position_size: 0.1
        stop_loss: 0.05
        take_profit: 0.1
      signals:
        buy: "price_below_mean_minus_std"
        sell: "price_above_mean_plus_std"
        exit: "price_crosses_mean"
        
    momentum:
      enabled: true
      description: "Momentum strategy"
      parameters:
        lookback_period: 20
        momentum_threshold: 0.02
        position_size: 0.1
        stop_loss: 0.05
        take_profit: 0.1
      signals:
        buy: "momentum_above_threshold"
        sell: "momentum_below_threshold"
        exit: "momentum_crosses_zero"
        
  # Ensemble strategies
  ensemble:
    enabled: true
    methods:
      weighted_average:
        enabled: true
        description: "Weighted average of strategy signals"
        
      majority_vote:
        enabled: true
        description: "Majority vote of strategy signals"
        min_agreement: 0.6
        
      consensus:
        enabled: true
        description: "Consensus-based signal generation"
        agreement_threshold: 0.7
        
    default_weights:
      bollinger_bands: 0.25
      macd: 0.25
      rsi: 0.25
      moving_average_crossover: 0.25
      
  # Risk management
  risk_management:
    enabled: true
    max_drawdown: 0.2
    max_daily_loss: 0.05
    max_position_risk: 0.02
    correlation_threshold: 0.7
    
    stop_loss:
      enabled: true
      default_stop_loss: 0.05
      trailing_stop: true
      trailing_distance: 0.02
      
    take_profit:
      enabled: true
      default_take_profit: 0.1
      trailing_take_profit: true
      trailing_distance: 0.02
      
  # Performance tracking
  performance:
    tracking_enabled: true
    metrics:
      - sharpe_ratio
      - sortino_ratio
      - calmar_ratio
      - max_drawdown
      - win_rate
      - profit_factor
      - total_return
      
    thresholds:
      min_sharpe_ratio: 0.5
      max_drawdown: 0.2
      min_win_rate: 0.4
      min_profit_factor: 1.2
      
  # Optimization
  optimization:
    enabled: true
    method: "bayesian"
    max_trials: 100
    timeout_minutes: 60
    objective: "maximize_sharpe_ratio"
    
    parameters:
      bollinger_bands:
        lookback_period: [10, 30]
        std_dev: [1.5, 2.5]
      macd:
        fast_period: [8, 16]
        slow_period: [20, 32]
      rsi:
        period: [10, 20]
        oversold_threshold: [20, 40]
        overbought_threshold: [60, 80]
        
  # Monitoring
  monitoring:
    enabled: true
    health_check_interval_minutes: 15
    performance_review_interval_days: 1
    strategy_rotation_check_interval_hours: 6
    
    alerts:
      enabled: true
      max_drawdown_alert: 0.15
      consecutive_losses_alert: 5
      performance_degradation_alert: 0.1 