version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  json:
    class: trading.utils.logging.StructuredFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: ${LOG_DIR}/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: ${LOG_DIR}/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  trading:
    level: ${LOG_LEVEL}
    handlers: [console, file, error_file]
    propagate: false

  trading.agents:
    level: ${AGENT_LOG_LEVEL}
    handlers: [console, file, error_file]
    propagate: false

  trading.models:
    level: ${MODEL_LOG_LEVEL}
    handlers: [console, file, error_file]
    propagate: false

  trading.data:
    level: ${DATA_LOG_LEVEL}
    handlers: [console, file, error_file]
    propagate: false

root:
  level: ${ROOT_LOG_LEVEL}
  handlers: [console, file] 