# Integration Test Configuration

# General Settings
timeout: 30  # seconds
retry_count: 3
retry_delay: 1  # seconds
parallel_tests: true
max_parallel_tests: 5
report_format: json
notify_on_failure: true

# Test Suites
test_suites:
  - id: system_integration
    name: System Integration Tests
    description: End-to-end system integration tests
    components:
      - api_gateway
      - service_registry
      - monitoring
      - logging
      - data_processing
      - notifications

  - id: component_tests
    name: Component Tests
    description: Individual component functionality tests
    components:
      - service_management
      - rbac
      - data_processing
      - notification
      - log_visualization

# Test Cases
test_cases:
  - id: api_gateway_health
    name: API Gateway Health Check
    description: Verify API Gateway is operational
    steps:
      - type: api_call
        method: GET
        url: /health
        expected_status: 200
        auth_required: true

  - id: service_registry_health
    name: Service Registry Health Check
    description: Verify Service Registry is operational
    steps:
      - type: api_call
        method: GET
        url: /services/health
        expected_status: 200
        auth_required: true

  - id: monitoring_health
    name: Monitoring System Health Check
    description: Verify Monitoring System is operational
    steps:
      - type: api_call
        method: GET
        url: /monitoring/health
        expected_status: 200
        auth_required: true

  - id: logging_health
    name: Logging System Health Check
    description: Verify Logging System is operational
    steps:
      - type: api_call
        method: GET
        url: /logging/health
        expected_status: 200
        auth_required: true

  - id: data_processing_health
    name: Data Processing Health Check
    description: Verify Data Processing System is operational
    steps:
      - type: api_call
        method: GET
        url: /data/health
        expected_status: 200
        auth_required: true

  - id: notification_health
    name: Notification System Health Check
    description: Verify Notification System is operational
    steps:
      - type: api_call
        method: GET
        url: /notifications/health
        expected_status: 200
        auth_required: true

# Component Tests
component_tests:
  - id: service_management_crud
    name: Service Management CRUD Operations
    description: Test service creation, reading, updating, and deletion
    steps:
      - type: api_call
        method: POST
        url: /services
        body:
          name: "test_service_${TEST_ID}"
          type: "test"
        expected_status: 201
        auth_required: true
      - type: api_call
        method: GET
        url: "/services/test_service_${TEST_ID}"
        expected_status: 200
        auth_required: true
      - type: api_call
        method: PUT
        url: "/services/test_service_${TEST_ID}"
        body:
          name: "test_service_${TEST_ID}"
          type: "test_updated"
        expected_status: 200
        auth_required: true
      - type: api_call
        method: DELETE
        url: "/services/test_service_${TEST_ID}"
        expected_status: 204
        auth_required: true

  - id: rbac_permissions
    name: RBAC Permission Tests
    description: Test role-based access control
    steps:
      - type: api_call
        method: POST
        url: /roles
        body:
          name: test_role
          permissions: ["read", "write"]
        expected_status: 201
      - type: api_call
        method: GET
        url: /roles/test_role
        expected_status: 200
      - type: api_call
        method: PUT
        url: /roles/test_role
        body:
          name: test_role
          permissions: ["read", "write", "delete"]
        expected_status: 200
      - type: api_call
        method: DELETE
        url: /roles/test_role
        expected_status: 204

  - id: data_processing_workflow
    name: Data Processing Workflow
    description: Test data processing pipeline
    steps:
      - type: api_call
        method: POST
        url: /data/process
        body:
          data_type: test
          content: "test data"
        expected_status: 202
      - type: api_call
        method: GET
        url: /data/status/test
        expected_status: 200

  - id: notification_delivery
    name: Notification Delivery
    description: Test notification system
    steps:
      - type: api_call
        method: POST
        url: /notifications
        body:
          type: test
          message: "Test notification"
          recipients: ["test@example.com"]
        expected_status: 202
      - type: api_call
        method: GET
        url: /notifications/status/test
        expected_status: 200

  - id: log_visualization
    name: Log Visualization
    description: Test log visualization features
    steps:
      - type: api_call
        method: POST
        url: /logs/visualize
        body:
          log_type: test
          visualization_type: "line_chart"
          time_range: "1h"
        expected_status: 200
      - type: api_call
        method: GET
        url: /logs/visualization/test
        expected_status: 200

# Expected Results
expected_results:
  api_gateway_health:
    status: "healthy"
    response_time: "< 100ms"
  
  service_registry_health:
    status: "healthy"
    registered_services: "> 0"
  
  monitoring_health:
    status: "healthy"
    metrics_collected: "> 0"
  
  logging_health:
    status: "healthy"
    log_entries: "> 0"
  
  data_processing_health:
    status: "healthy"
    processing_queue: "empty"
  
  notification_health:
    status: "healthy"
    delivery_queue: "empty"

# Notification Settings
notifications:
  on_failure:
    email:
      enabled: true
      recipients:
        - "${TEST_EMAIL_RECIPIENT}"
    slack:
      enabled: true
      channel: "${TEST_SLACK_CHANNEL}"
  
  on_success:
    email:
      enabled: false
    slack:
      enabled: true
      channel: "${TEST_SLACK_CHANNEL}"

# Reporting Settings
reporting:
  format: json
  location: "automation/reports"
  retention_days: 30
  include_details: true
  include_metrics: true
  include_logs: true 